#!/bin/bash

BGreen='\033[1;32m'
NC='\033[0m' # No Color

echo -e "${BGreen}Please enter the dbuser/password you would like to use. The sed script will replace all instances of "nostr_ts_relay" with your chosen username/password. Please enter only one word to be both the username and password${NC}"
read ANSWER
#cd ..
sed -i "s/nostr_ts_relay/$ANSWER/g" ../docker-compose.yml

